const styles = {
    wrapper: {
      backgroundColor: 'black',
      color: '#fff',
      position: 'fixed',
      inset: 0,
      zIndex: 9999,
      display: 'flex',
      flexDirection: 'column',
    },
    topBar: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '10px 15px',
      backgroundColor: 'rgba(0,0,0,0.7)',
    },
    iconBtn: {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      color: '#fff',
      fontSize: '1.2rem',
    },
    topLine: {
      position: 'absolute',
      top: 0,
      width: '2px',
      height: '4px',
      backgroundColor: '#fff',
      zIndex: 2,
    },
    thumbnailStrip: {
      height: 60,
      backgroundColor: '#222',
      overflowX: 'auto',
      display: 'flex',
      alignItems: 'center',
      padding: '5px 15px',
      position: 'relative',
    },
    scrubberLine: {
      position: 'absolute',
      top: 5,
      width: '2px',
      height: '60px',
      backgroundColor: '#fff',
      zIndex: 1,
      pointerEvents: 'none',
    },
    mediaArea: {
      flex: 1,
      position: 'relative',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#000',
      overflow: 'hidden',
    },
    video: {
      width: '100%',
      height: '100%',
      objectFit: 'contain',
    },
    drawingCanvas: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      touchAction: 'none',
    },
    controls: {
      display: 'flex',
      justifyContent: 'center',
      gap: 20,
      padding: '10px 0',
    },
    captionArea: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      padding: '0 15px',
    },
    input: {
      flex: 1,
      padding: '8px 12px',
      backgroundColor: '#222',
      border: 'none',
      borderRadius: 16,
      color: '#fff',
      fontSize: '0.9rem',
    },
    
    sendBtn: {
      backgroundColor: '#007bff',
      border: 'none',
      borderRadius: '50%',
      padding: '10px',
      color: '#fff',
      cursor: 'pointer',
      width: 40,
      height: 40,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    footer: {
      display: 'flex',
      justifyContent: 'space-between',
      fontSize: 12,
      color: '#ccc',
      padding: '0 15px 10px',
    },
    colorStrip: {
      position: 'absolute',
      top: 50,
      left: 33,
      display: 'flex',
      flexDirection: 'column',
      gap: 5,
      overflowY: 'auto',
      maxHeight: 'calc(100vh - 100px)',
      padding: '10px 15px',
      backgroundColor: 'transparent',
      zIndex: 1000,
    },
    colorDot: {
      width: 18,
      height: 18,
      borderRadius: '50%',
      border: '2px solid #fff',
      cursor: 'pointer',
      boxSizing: 'border-box',
    },
    drawingTools: {
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      padding: '10px 0',
    },
    thicknessSelector: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 15,
      padding: '0 15px',
    },
    thicknessBtn: {
      padding: '5px 15px',
      borderRadius: 5,
      border: 'none',
      color: '#fff',
      cursor: 'pointer',
      width: 60,
      textAlign: 'center',
      backgroundColor: '#444',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
  };
  
  export default styles;